### ISSUE TITLE
try.haxe.org not compiling

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/haxe.org#253]
Hitting Build / Run just freezes at "compiling...", no output is ever observed.

![image](https://cloud.githubusercontent.com/assets/2192439/23756195/21d2af4c-04a0-11e7-9dc4-b5e8ea215b2c.png)

Check on the compiler server?

Sorry if this isn't the right repo for this issue.

**Comment by jcward** [comment]
Ah, the console dumps a stack trace. Maybe it's out of disk space? Seems like it can't write the temp file:

```
"Invalid response : '<pre>uncaught exception: <b>Cannot serialize exception 'HException' with message 'file_put_contents(../tmp/54F4A/Test.hx) [<a href='function.file-put-contents'>function.file-put-contents</a>]: failed to open stream: No such file or directory (errno: 2)' in /srv/d_nina/try-haxe/app/lib/sys/io/File.class.php:10
Stack trace:
#0 [internal function]: _hx_error_handler(2, 'file_put_conten...', '/srv/d_nina/try...', 10, Array)
#1 /srv/d_nina/try-haxe/app/lib/sys/io/File.class.php(10): file_put_contents('../tmp/54F4A/Te...', 'class Test {?  ...')
#2 /srv/d_nina/try-haxe/app/lib/api/Compiler.class.php(78): sys_io_File::saveContent('../tmp/54F4A/Te...', 'class Test {?  ...')
#3 /srv/d_nina/try-haxe/app/lib/api/Compiler.class.php(281): api_Compiler->prepareProgram(Object(_hx_anonymous))
#4 [internal function]: api_Compiler->compile(Object(_hx_anonymous))
#5 /srv/d_nina/try-haxe/app/lib/Reflect.class.php(10): call_user_func_array(Array, Array)
#6 /srv/d_nina/try-haxe/app/lib/haxe/remoting/Context.class.php(40): Reflect::callMethod(Object(api_Compiler), Array, Object(_hx_array))
#7 /srv/d_nina/try-haxe/app/lib/haxe/remoting/HttpConnection.class.php(40): haxe_remoting_Context->call(Object(_hx_array), Object(_hx_array))
#8 /srv/d_nina/try-haxe/app/lib/haxe/remoting/HttpConnection.class.php(33): haxe_remoting_HttpConnection::processRequest('ay8:Compilery7:...', Object(haxe_remoting_Context))
#9 /srv/d_nina/try-haxe/app/lib/Api.class.php(11): haxe_remoting_HttpConnection::handleRequest(Object(haxe_remoting_Context))
#10 [internal function]: Api->doCompiler()
#11 /srv/d_nina/try-haxe/app/lib/Reflect.class.php(10): call_user_func_array(Array, Array)
#12 /srv/d_nina/try-haxe/app/lib/haxe/web/Dispatch.class.php(66): Reflect::callMethod(Object(Api), Array, Object(_hx_array))
#13 /srv/d_nina/try-haxe/app/lib/App.class.php(25): haxe_web_Dispatch->runtimeDispatch(Object(_hx_anonymous))
#14 /srv/d_nina/try-haxe/app/index.php(11): App::main()
#15 {main}</b><br /><br />in file: /srv/d_nina/try-haxe/app/lib/haxe/Serializer.class.php line 428<br />#0 /srv/d_nina/try-haxe/app/lib/haxe/Serializer.class.php(434): haxe_Serializer->serialize(Object(HException))
#1 /srv/d_nina/try-haxe/app/lib/haxe/remoting/HttpConnection.class.php(49): haxe_Serializer->serializeException(Object(HException))
#2 /srv/d_nina/try-haxe/app/lib/haxe/remoting/HttpConnection.class.php(33): haxe_remoting_HttpConnection::processRequest('ay8:Compilery7:...', Object(haxe_remoting_Context))
#3 /srv/d_nina/try-haxe/app/lib/Api.class.php(11): haxe_remoting_HttpConnection::handleRequest(Object(haxe_remoting_Context))
#4 [internal function]: Api->doCompiler()
#5 /srv/d_nina/try-haxe/app/lib/Reflect.class.php(10): call_user_func_array(Array, Array)
#6 /srv/d_nina/try-haxe/app/lib/haxe/web/Dispatch.class.php(66): Reflect::callMethod(Object(Api), Array, Object(_hx_array))
#7 /srv/d_nina/try-haxe/app/lib/App.class.php(25): haxe_web_Dispatch->runtimeDispatch(Object(_hx_anonymous))
#8 /srv/d_nina/try-haxe/app/index.php(11): App::main()
#9 {main}</pre>'"
```

**Comment by Gama11** [comment]
In the menatime, http://try-haxe.mrcdk.com/ still appears to work fine.

**Comment by markknol** [comment]
Or you run your own local build

**Comment by jcward** [comment]
Seems to be working today. I wonder if it was temporary, or if someone nudged the server. Anyway, I'll close this.

**Comment by ibilon** [comment]
@clemos said on twitter that the disk was full (your hypothesis was right) and he clean up some space
